---
title: "Walking"
output: html_notebook
---

```{r}
#check working directory
setwd("C:/Users/hanji/Desktop/Workshop/Foldable_Spaces/Data")
#setwd("C:/Users/Jihae Han/Desktop/Projects/Foldable_Spaces/Data")
getwd()
library(ggplot2)
library(dplyr)
library(gtools)
library(ggpubr)
library(likert)
```

```{r}
#auxiliary functions
file2id <- function(s) {
  as.integer(substr(s,1,3))
}
file2walking <- function (input, condition, namingcontainer){
  cbind(lapply(input, file2id), rep(condition, length(input)), input)
}
getrowindex <- function(container, id, condition){
  tempcontainer <- container[which(container$Condition==condition),]
  tempcontainer <- tempcontainer[tempcontainer$ID==id,]
  as.integer(rownames(tempcontainer))  
}

```

```{r}
#Load data and fix user input errors
raw = read.csv("results_survey.csv")
offset = 69-33
raw[c(1)] <- seq(1,nrow(raw))
raw[1,33] <- "AO04"

#Organise spatial metrics
COGspatial = data.frame(ID=NA, Condition=NA, RoomSize=NA, Walked=NA)
COGspatial <- COGspatial[FALSE,]

spatial1 <- raw[c(1,33:35)]
spatial2 <- raw[c(1,33:35+offset)]
spatial3 <- raw[c(1,33:35+offset*2)]
spatial4 <- raw[c(1,33:35+offset*3)]

names(spatial1) <- names(COGspatial)
names(spatial2) <- names(COGspatial)
names(spatial3) <- names(COGspatial)
names(spatial4) <- names(COGspatial)

COGspatial <- rbind(COGspatial, spatial1)
COGspatial <- rbind(COGspatial, spatial2)
COGspatial <- rbind(COGspatial, spatial3)
COGspatial <- rbind(COGspatial, spatial4)

COGspatial[2] <- sapply(COGspatial$Condition, code2trial)
for (i in 1:nrow(COGspatial)) {
  c <- ""
  if (i <= 20) {
    c <- switch(COGspatial[i,]$ID%%4+1,"S&R", "Acc", "Ver", "Hor")
  }
  else if (i <= 40) {
    c <- switch(COGspatial[i,]$ID%%4+1, "Acc", "Ver", "Hor", "S&R")
  }
  else if (i <= 60) {
    c <- switch(COGspatial[i,]$ID%%4+1, "Ver", "Hor", "S&R", "Acc")
  }
  else {
    c <- switch(COGspatial[i,]$ID%%4+1, "Hor", "S&R", "Acc", "Ver")
  }
  COGspatial[i,]$Condition <- c
}
#COG1: "how many times larger than the physical environment is the virtual environment? 
gtcog1 = 96/16
COGspatial$AccuracyRoom <- (COGspatial$RoomSize-gtcog1)/gtcog1 * 100

#stats
friedman.test(AccuracyRoom ~ Condition | ID, data = COGspatial) 
res.aov <- aov(AccuracyRoom ~ Condition, data = COGspatial)
summary(res.aov)

pw_accuracyroom <- pairwise.wilcox.test(COGspatial$AccuracyRoom, COGspatial$Condition, p.adjust.method = "bonferroni", paired = TRUE)
pw_accuracyroom
createBoxplot(COGspatial,'AccuracyRoom',"Room Accuracy",pw_accuracyroom)


```

```{r}
#list&organise all files in folder
walking = data.frame(ID=NA, Condition=NA, Path=NA)
walking <- walking[FALSE,]

acc_path <- list.files(path = ".", pattern = "1AccordionTest")
ver_path <- list.files(path = ".", pattern = "2VertTest")
hor_path <- list.files(path = ".", pattern = "3HoriTest")
snr_path <- list.files(path = ".", pattern = "4StopFadeReset")

acc_raw <- file2walking(acc_path, "Acc", walking)
ver_raw <- file2walking(ver_path, "Ver", walking)
hor_raw <- file2walking(hor_path, "Hor", walking)
snr_raw <- file2walking(snr_path, "S&R", walking)

walking <- rbind(walking, acc_raw)
walking <- rbind(walking, ver_raw)
walking <- rbind(walking, hor_raw)
walking <- rbind(walking, snr_raw)

colnames(walking) <- c("ID", "Condition", "Path")

#Compute Data for Walking and organise dataframes into larger dataframe
walkdata <- data.frame(ID=NA, Condition=NA, Time=NA, X=NA, Y=NA, Dist=NA, Velo=NA, Acce=NA)
walking$Walked <- 0 #Walked is cognitive user estimation
for (i in 1:nrow(walking)){
  walking[i,]$Walked <- COGspatial[getrowindex(COGspatial, walking[i,]$ID, walking[i,]$Condition),]$Walked 
}

walking$TotalWalked <- 0
walking$TotalTime <- 0
walking$AveSpeed <- 0
walking$MaxSpeed <- 0
walking$MinAccel <- 0
walking$MaxAccel <- 0
walking$CountGait <- 0

walksample =data.frame(Time=NA, X=NA, Y=NA, Dist=NA, Velo=NA, Acce=NA)
for (i in 1:1){
  tempwalk <- read.csv(toString(walking[i,]$Path), header = FALSE, sep = ",")
  tempwalk <- tempwalk[c(2:4)]
  colnames(tempwalk) <- c("Time", "X", "Y")
  tempwalk$Dist <- 0
  tempwalk$Velo <- 0
  tempwalk$Acce <- 0
  #distance
  for (x in 2:nrow(tempwalk)){
    tempwalk$Dist[x] <- sqrt((tempwalk$X[x]-tempwalk$X[x-1])^2 + (tempwalk$Y[x]-tempwalk$Y[x-1])^2)
  }
  tempwalk <- tempwalk[as.integer(which(tempwalk$Dist==max(tempwalk$Dist))):(nrow(tempwalk)-10*60),]
  #tighten to 3min
  if (tempwalk$Time[nrow(tempwalk)]-tempwalk$Time[1]>0) {
    tempwalk <- tail(tempwalk, 3*60*60)
  }
  #velocity
  for (x in 2:nrow(tempwalk)){
    if(tempwalk$Time[x]==tempwalk$Time[x-1]) {
      tempwalk$Velo[x] <- tempwalk$Velo[x-1]
    }
    else {
      tempwalk$Velo[x] <- tempwalk$Dist[x]/(tempwalk$Time[x]-tempwalk$Time[x-1])
    }
  }
  #acceleration
  for (x in 3:nrow(tempwalk)) {
    if (tempwalk$Time[x]==tempwalk$Time[x-1])
    {
      tempwalk$Acce[x] <- tempwalk$Acce[x-1]
    }
    else{
      tempwalk$Acce[x] <- (tempwalk$Velo[x]-tempwalk$Velo[x-1])/(tempwalk$Time[x]- tempwalk$Time[x-1])
    }
  }
  walkdata <- rbind(c(walking$ID[i], walking$Condition[i],tempwalk))
  walking[i,]$TotalWalked <- sum(tempwalk$Dist)/100
  walking[i,]$TotalTime <- (tempwalk$Time[nrow(tempwalk)]-tempwalk$Time[1])/60 
  walking[i,]$AveSpeed <- walking[i,]$TotalWalked/walking[i,]$TotalTime * (1/60)
  walking[i,]$MaxSpeed <- max(tempwalk$Velo) * (1/100) 
  walking[i,]$MinAccel <- min(tempwalk$Acce) * (1/100)
  walking[i,]$MaxAccel <- max(tempwalk$Acce) * (1/100)
}

for (i in 2:nrow(walking)){
  tempwalk <- read.csv(toString(walking[i,]$Path), header = FALSE, sep = ",")
  tempwalk <- tempwalk[c(2:4)]
  colnames(tempwalk) <- c("Time", "X", "Y")
  tempwalk$Dist <- 0
  tempwalk$Velo <- 0
  tempwalk$Acce <- 0
  #distance
  for (x in 2:nrow(tempwalk)){
    tempwalk$Dist[x] <- sqrt((tempwalk$X[x]-tempwalk$X[x-1])^2 + (tempwalk$Y[x]-tempwalk$Y[x-1])^2)
  }
  tempwalk <- tempwalk[as.integer(which(tempwalk$Dist==max(tempwalk$Dist))):(nrow(tempwalk)-10*60),]
  #tighten to 3min
  if (tempwalk$Time[nrow(tempwalk)]-tempwalk$Time[1]>0) {
    tempwalk <- tail(tempwalk, 3*60*60)
  }
  #velocity
  for (x in 2:nrow(tempwalk)){
    if(tempwalk$Time[x]==tempwalk$Time[x-1]) {
      tempwalk$Velo[x] <- tempwalk$Velo[x-1]
    }
    else {
      tempwalk$Velo[x] <- tempwalk$Dist[x]/(tempwalk$Time[x]-tempwalk$Time[x-1])
    }
  }
  #acceleration
  for (x in 3:nrow(tempwalk)) {
    if (tempwalk$Time[x]==tempwalk$Time[x-1])
    {
      tempwalk$Acce[x] <- tempwalk$Acce[x-1]
    }
    else{
      tempwalk$Acce[x] <- (tempwalk$Velo[x]-tempwalk$Velo[x-1])/(tempwalk$Time[x]- tempwalk$Time[x-1])
    }
  }

  walkdata <- rbind(walkdata,c(walking$ID[i], walking$Condition[i],tempwalk))
  walking[i,]$TotalWalked <- sum(tempwalk$Dist)/100
  walking[i,]$TotalTime <- (tempwalk$Time[nrow(tempwalk)]-tempwalk$Time[1])/60 
  walking[i,]$AveSpeed <- walking[i,]$TotalWalked/walking[i,]$TotalTime * (1/60)
  walking[i,]$MaxSpeed <- max(tempwalk$Velo) * (1/100) 
  walking[i,]$MinAccel <- min(tempwalk$Acce) * (1/100)
  walking[i,]$MaxAccel <- max(tempwalk$Acce) * (1/100)
  
}
```

```{r}
#------Distance Accuracy------#
COGspatial$TotalWalked <- 0
COGspatial$AccuracyWalked <- 0
COGspatial$TotalTime <- 0


#CHECK DATA for (might be another file missing): 
# 9, "Hor"
# 11, "Acc" 

for (i in 1:nrow(COGspatial)){
  index = getrowindex(walking, COGspatial[i,]$ID, COGspatial[i,]$Condition)
  if (length(index)>1){
    temptime <- 0 
    for (e in 1:length(index)) {
      if (temptime < 3.1){
        if (temptime + walking[index[e],]$TotalTime < 3.1) {
          COGspatial[i,]$TotalWalked <- walking[index[e],]$TotalWalked + COGspatial[i,]$TotalWalked
          temptime <- temptime + walking[index[e],]$TotalTime
        }
        else {
          COGspatial[i,]$TotalWalked <- COGspatial[i,]$TotalWalked + tail(walking[index[e],]$TotalWalked, (3-temptime)*60*60)
          temptime <- temptime + (3-temptime)
        }
      }
    }
    COGspatial[i,]$TotalTime <- temptime
  }
  else if (length(index)>0){
    COGspatial[i,]$TotalWalked <- walking[index,]$TotalWalked
    COGspatial[i,]$TotalTime <- walking[index,]$TotalTime
  }
}

COGspatial$AccuracyWalked <- (COGspatial$Walked-COGspatial$TotalWalked)/COGspatial$TotalWalked

#stats
friedman.test(AccuracyWalked ~ Condition | ID, data = COGspatial) 

friedman.test(TotalWalked ~ Condition | ID, data = COGspatial) 
pw_twalked <- pairwise.wilcox.test(COGspatial$TotalWalked, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_twalked
createBoxplot(COGspatial,'TotalWalked',"Total Walked Distance",pw_twalked)

pw_awalked <- pairwise.wilcox.test(COGspatial$AccuracyWalked, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_awalked
createBoxplot(COGspatial,'AccuracyWalked',"Accuracy Walked Distance",pw_awalked)


```

```{r}
#--------Velocity, Ave & Max (m/s)---------#
COGspatial$AveSpeed <- 0
COGspatial$MaxSpeed <- 0

for (i in 1:nrow(COGspatial)){
  index = getrowindex(walking, COGspatial[i,]$ID, COGspatial[i,]$Condition)
  if (length(index)>1){
    sumtime <- sum(walking[index,]$TotalTime*60)
    COGspatial[i,]$AveSpeed <- sum(walking[index,]$AveSpeed*walking[index,]$TotalTime*60)/(sumtime)
    COGspatial[i,]$MaxSpeed <- max(walking[index,]$MaxSpeed)
  }
  else if (length(index)>0){
    COGspatial[i,]$AveSpeed <- walking[index,]$AveSpeed
    COGspatial[i,]$MaxSpeed <- walking[index,]$MaxSpeed
  }
}

#stats
friedman.test(AveSpeed ~ Condition | ID, data = COGspatial) 
friedman.test(TotalWalked ~ Condition | ID, data = COGspatial) 

pw_avespeed <- pairwise.wilcox.test(COGspatial$AveSpeed, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_avespeed
createBoxplot(COGspatial,'AveSpeed',"Average Speed (m/s)",pw_avespeed)


pw_maxspeed <- pairwise.wilcox.test(COGspatial$MaxSpeed, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_maxspeed
createBoxplot(COGspatial,'MaxSpeed',"Max Speed (m/s)",pw_maxspeed)

summarise(coggroup1, mSpeed=mean(AveSpeed), sdSpeed=sd(AveSpeed),mMaxSpeed=mean(MaxSpeed), sdMaxSpeed=sd(MaxSpeed))

```

```{r}
#--------Min/Max Acceleration (m/s^2)---------# Not Useful
COGspatial$MinAccel <- 0
COGspatial$MaxAccel <- 0

for (i in 1:nrow(COGspatial)){
  index = getrowindex(walking, COGspatial[i,]$ID, COGspatial[i,]$Condition)
  if (length(index)>1){
    COGspatial[i,]$MinAccel <- min(walking[index,]$MinAccel)
    COGspatial[i,]$MaxAccel <- max(walking[index,]$MaxAccel)
  }
  else if (length(index)>0){
    COGspatial[i,]$MinAccel <- walking[index,]$MinAccel
    COGspatial[i,]$MaxAccel <- walking[index,]$MaxAccel
  }
}

#stats
friedman.test(MinAccel ~ Condition | ID, data = COGspatial) 
friedman.test(MaxAccel ~ Condition | ID, data = COGspatial) 

pw_minaccel <- pairwise.wilcox.test(COGspatial$MinAccel, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_minaccel
createBoxplot(COGspatial,'MinAccel',"Max Decceleration (m/s^2)",pw_minaccel)

pw_maxaccel <- pairwise.wilcox.test(COGspatial$MaxAccel, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_maxaccel
createBoxplot(COGspatial,'MaxSpeed',"Max Acceleration (m/s)",pw_maxaccel)
```

```{r}
#--------Changes in Acceleration (m/s^2) to calculate continuous movement ---#
checksign <- function(value) {
  if (value >= 0)
    return(TRUE)
  else (value < 0)
    return(FALSE)
}

#calculate changes in acceleration
for (i in 1:nrow(walkdata)) { #nrow(walkdata)
  count <- 0 
  tempcount <- 0
  currentaccel <- TRUE
  for (index in 2:length(walkdata[i,]$Acce)) {
    if (checksign(walkdata[i,]$Acce[index]) != checksign(walkdata[i,]$Acce[index-1])) {
      tempcount <- tempcount + 1
      if (tempcount > 59) { #if the acceleration/decceration is more than a second 
        count <- count + 1
        tempcount <- 0
      }
    }
  }
  walking[i,]$CountGait <- count
}

#input into COGspatial
COGspatial$CountGait <- 0
for (i in 1:nrow(COGspatial)){
  index = getrowindex(walking, COGspatial[i,]$ID, COGspatial[i,]$Condition)
  if (length(index)>1){
    COGspatial[i,]$CountGait <- sum(walking[index,]$CountGait)
  }
  else if (length(index)>0){
    COGspatial[i,]$CountGait <- walking[index,]$CountGait
  }
  COGspatial[i,]$CountGait <- COGspatial[i,]$CountGait/
    (COGspatial[i,]$TotalTime*60)
}
#stats
friedman.test(CountGait ~ Condition | ID, data = COGspatial) 

pw_countgait <- pairwise.wilcox.test(COGspatial$CountGait, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_countgait
createBoxplot(COGspatial,'CountGait',"Changes in Walking Gait per Second",pw_countgait)
```

```{r}
#-------------Calculations of rest (idle time)-----------#
threshold = 10 #cm/s

walking$CountRest <- 0
walking$Idle <- 0
for (i in 1:nrow(walkdata)) {
  temptime <- 0
  idlecheck <- 0
  idletime <- 0
  for (index in 2:length(walkdata[i,]$Velo)) {
    if (walkdata[i,]$Velo[index] < threshold){
      temptime <- temptime + walkdata[i,]$Time[index]-walkdata[i,]$Time[index-1]
      idletime <- idletime + walkdata[i,]$Time[index]-walkdata[i,]$Time[index-1]
    }
    else {
      if (idletime > idlecheck) {
        idlecheck <- idletime
      }
      else {
        idletime <- 0
      }
    }
  }
  walking[i,]$CountRest <- idlecheck
  walking[i,]$Idle <- temptime
}

#input into COGspatial
COGspatial$CountRest <- 0
COGspatial$Idle <- 0
for (i in 1:nrow(COGspatial)){
  index = getrowindex(walking, COGspatial[i,]$ID, COGspatial[i,]$Condition)
  if (length(index)>1){
    COGspatial[i,]$Idle <- sum(walking[index,]$Idle)/sum(walking[index,]$TotalTime)
    COGspatial[i,]$CountRest <- max(walking[index,]$CountRest)
  }
  else if (length(index)>0){
    COGspatial[i,]$Idle <- walking[index,]$Idle/walking[index,]$TotalTime
    COGspatial[i,]$CountRest <- walking[index,]$CountRest
  }
  COGspatial[i,]$Idle <- COGspatial[i,]$Idle/60*100
}

#stats
friedman.test(Idle ~ Condition | ID, data = COGspatial) 
friedman.test(CountRest ~ Condition | ID, data = COGspatial) 

pw_idle <- pairwise.wilcox.test(COGspatial$Idle, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_idle
createBoxplot(COGspatial,'Idle',"Idle Time (%)",pw_idle)

pw_countrest <- pairwise.wilcox.test(COGspatial$CountRest, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_countrest
createBoxplot(COGspatial,'CountRest',"Max Idle (sec)",pw_countrest)

```

```{r}
#--------------Idle Count--------------------#
threshold = 10 #cm/sec
pausethreshold = 1 #sec

walking$IdleCount <- 0

for (i in 1:nrow(walkdata)) {
  idlecount <- 0
  temptime <- 0
  for (index in 2:length(walkdata[i,]$Velo)) {
    if (walkdata[i,]$Velo[index] < threshold){
      temptime <- temptime + walkdata[i,]$Time[index]-walkdata[i,]$Time[index-1]
    }
    else {
      if (temptime > pausethreshold) {
        temptime <- 0
        idlecount <- idlecount + 1
      }
    }
  }
  walking[i,]$IdleCount <- idlecount
  walking[i,]$Idle <- temptime
}

COGspatial$IdleCount <- 0
for (i in 1:nrow(COGspatial)){
  index = getrowindex(walking, COGspatial[i,]$ID, COGspatial[i,]$Condition)
  if (length(index)>1){
    COGspatial[i,]$IdleCount <- sum(walking[index,]$IdleCount)
  }
  else if (length(index)>0){
    COGspatial[i,]$IdleCount <- walking[index,]$IdleCount
  }
  COGspatial[i,]$IdleCount <- COGspatial[i,]$IdleCount/(COGspatial[i,]$TotalTime*60)
}

#stats
friedman.test(IdleCount ~ Condition | ID, data = COGspatial) 

pw_idlecount <- pairwise.wilcox.test(COGspatial$IdleCount, COGspatial$Condition,
                           p.adjust.method = "bonferroni",
                           paired = TRUE)
pw_idlecount
createBoxplot(COGspatial,'IdleCount',"Rests per Second",pw_idlecount)

```

```{r}
#---------------Out of Bounds------------------#
walking$CountHelp <- 0
padding <- 10 #cm, rounding up from the radius of human head with 60cm circ.

for (i in 1:nrow(walkdata)) {  #Hor only = 46:68 #all = 1:nrow(walkdata)
  count <- 0 
  isout <- FALSE
  bfout <- FALSE
  for (index in 1:length(walkdata[i,]$X)) {
    if (walking[i,]$Condition != "Hor") {
      if ((walkdata[i,]$X[index] > 190) || (walkdata[i,]$Y[index]> 190) || (walkdata[i,]$X[index] < -190) || (walkdata[i,]$Y[index] < -190) ) {
        bfout <- isout
        isout <- TRUE
        if (bfout != isout) {
          count <- count + 1
        }
      }
      else{
        bfout <- isout
        isout <- FALSE
      }
    }
    else if (walking[i,]$Condition == "Hor"){
      if ((walkdata[i,]$X[index] > 390 || walkdata[i,]$X[index] < 10 || walkdata[i,]$Y[index] > 190) || walkdata[i,]$Y[index] < -190) {
        bfout <- isout
        isout < TRUE
        if (bfout != isout) {
          cout <- count + 1
        }
        else {
          bfout <- isout
          isout <- FALSE
        }
      }
    }
  }
  walking[i,]$CountHelp <- count
}
```

```{r}
#---------Graph: Out of Bounds--------#
#Fix False Positives
walking[1:25,]$CountHelp <- 0
walking[72,]$CountHelp <- 1
walking[79,]$CountHelp <- 0
walking[39,]$CountHelp <- 1
walking[83,]$CountHelp <- 1
walking[85,]$CountHelp <- 1

#setup COGspatial input
COGspatial$CountHelp <- 0

for (i in 1:nrow(COGspatial)){
  index = getrowindex(walking, COGspatial[i,]$ID, COGspatial[i,]$Condition)
  if (length(index)>1){
    COGspatial[i,]$CountHelp <- sum(walking[index,]$CountHelp)
  }
  else if (length(index)>0){
    COGspatial[i,]$CountHelp <- walking[index,]$CountHelp
  }
}

#stats
friedman.test(CountHelp ~ Condition | ID, data = COGspatial)
res.aov <- aov(CountHelp ~ Condition, data = COGspatial)
summary(res.aov)

res.fried <- COGspatial %>% friedman_test(CountHelp ~ Condition | ID)
res.fried

COGspatial %>% friedman_effsize(CountHelp ~ Condition |ID)

#pwc <- COGspatial %>% wilcox_test(CountHelp ~ Condition, paired = TRUE,
pwc <- COGspatial %>% sign_test(CountHelp ~ Condition, 
                 p.adjust.method = "bonferroni")
                 
pwc


pwc <- pwc %>% add_xy_position(x = "Condition")
ggboxplot(COGspatial, x = "Condition", y = "CountHelp", add = "point") +
  stat_pvalue_manual(pwc, hide.ns = TRUE) +
  labs(
    subtitle = get_test_label(res.fried,  detailed = TRUE),
    caption = get_pwc_label(pwc)
  )

#pw_counthelp <- pairwise.wilcox.test(COGspatial$CountHelp, COGspatial$Condition,
#                           p.adjust.method = "bonferroni",
#                           paired = TRUE,)
#pw_counthelp
#createBoxplot(COGspatial,'CountHelp',"Walking Out of Bounds (count)",pw_counthelp)

#pwc <- COGspatial %>% wilcox_test(CountHelp ~ Condition, paired = TRUE,
#pwc <- COGspatial %>% sign_test(CountHelp ~ Condition, 
                 #p.adjust.method = "bonferroni")
                 
#pwc

summarise(COGspatial, )
```

```{r}
#--------example of graphs--------#
tempwalk <- walkdata[79,]
plot(tempwalk$X,tempwalk$Y, main = paste("Walk Position"), xlab = "X", ylab = "y")

plot(tempwalk$Time, tempwalk$Velo/100, main = paste("Velocity"), xlab = "Time(s)", ylab = "Velocity(m/s)", cex=.75)

plot(tempwalk$Time, tempwalk$Acce/100, main = paste("Acceleration"), xlab = "Time(s)", ylab = "Acceleration(m/s)", cex=.75)
```

```{r}
save_plots <- TRUE

savePlot <- function(plotName){
  if(save_plots){
    ggsave(paste(".\\Plots\\",plotName,".png",sep=""),
           width=14, 
           height = 14,
           units= "cm")
  }
}

createBoxplot(COGspatial,'AveSpeed',"Mean Velocity (m/s)",pw_avespeed)
savePlot("Velocity")

createBoxplot(COGspatial,'CountGait',"Changes in Gait per Second",pw_countgait)
savePlot("Gait")

createBoxplot(COGspatial,'Idle',"Idle Time (%)",pw_idle)
savePlot("IdleTime")

createBoxplot(COGspatial,'IdleCount',"Rests per Second",pw_idlecount)
savePlot("IdleCount")





```

```{r}
coggroup1 = COGspatial %>% group_by(Condition)
summarise(coggroup1, mSpeed=mean(AveSpeed), sdSpeed=sd(AveSpeed),mMaxSpeed=max(AveSpeed))
summarise(coggroup1, mGait=mean(CountGait), sdGait=sd(CountGait),)

summarise(coggroup1, mIdle=mean(Idle), sdIdle=sd(Idle), maxIdle=max(Idle), maxRest=mean(CountRest))

summarise(coggroup1, mFreq=mean(IdleCount), sdFreq=sd(IdleCount))


summarise(coggroup1, mSafe=mean(CountHelp), sdSafec=sd(CountHelp))


```

```{r}
#-----Calculate Max Speed -------#
walking$Max2 <- 0
COGspatial$Max2 <- 0

for (i in 1:nrow(walkdata)) { #nrow(walkdata)
 walking[i,]$Max2 <- 
   max(walkdata[i,]$Velo[which(walkdata[i,]$Velo < mean(walkdata[i,]$Velo)*2)])
}

for (i in 1:nrow(COGspatial)){
  index = getrowindex(walking, COGspatial[i,]$ID, COGspatial[i,]$Condition)
  COGspatial[i,]$Max2 <- max(walking[index,]$Max2)
}
friedman.test(Max2 ~ Condition | ID, data = COGspatial)
coggroup1 = COGspatial %>% group_by(Condition)
summarise(coggroup1, m(Max2), sdSpeed=sd(Max2))
```
